### ISSUE TITLE
Cannot download hugginface transformers models

### ISSUE THREAD

**Issue by cth127** [AIML-K/bamboo-forest#144]
무슨 이유인지에서는 모르겠으나, 연구실 네트워크 상에서 huggingface transformers 모델을 받을 수 없는 문제가 있습니다. 지금까지 발견된 현상으로는,

1. 작은 파일들은 다운로드가 되지만 모델 파라미터같은 큰 파일은 다운로드가 안 됨.
2. 607 내 유선망을 활용하는 로컬 머신과, 또 다른 유선망을 활용하는 Ambers에서 다운로드 안 됨.
3. AIL-K5G, KoreaUnivAP 무선망에서는 됨. (학교 단위에서 막힌 건 아니고, 연구실 내부 망에서 막힌다는 뜻)
4. huggingface 홈페이지에서 직접 다운받는 것도 안 되고, 터미널에서 wget 하는 것도, from_pretrained로 받는 것도 안 됨. 아래와 같은 에러가 뜸
5. 큰 파일을 받는 거 자체가 문제는 아님, 다른 페이지에선 큰 파일을 잘 받을 수 있음.

```txt
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fec4734ff10>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Max retries exceeded with url: /bert-base-uncased/68d45e234eb4a928074dfd868cead0219ab85354cc53d20e772753c6bb9169d3?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27model.safetensors%3B+filename%3D%22model.safetensors%22%3B&Expires=1698901905&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5ODkwMTkwNX19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9iZXJ0LWJhc2UtdW5jYXNlZC82OGQ0NWUyMzRlYjRhOTI4MDc0ZGZkODY4Y2VhZDAyMTlhYjg1MzU0Y2M1M2QyMGU3NzI3NTNjNmJiOTE2OWQzP3Jlc3BvbnNlLWNvbnRlbnQtZGlzcG9zaXRpb249KiJ9XX0_&Signature=nO9ftAyr7QE8jCpcduTOKYQNT5Ty3o1MHjuMc6QVD6efkvXWzkxG7ZslK~ECruDr-0yJLUwJ~yTOdjkpXR9X5p16C5MPI-WEzsjnnEI7EDTrQawa~-DXdv6~6ljqneW0DHGbBuBke8~yL2sIkcniDZXYeGWD-Wy2PhDZd3-t~T0qC44lRGZqalrjN4RZMB6hWrWLlT2oK98RcH2BJd6IZmP8nwVJfHSLQdsDy3zIkA33MWNhO0e5x7aK33Fr610Jj2wY0CPu81rZw9fhzZZbX~6Ke4LwWCR0ob8CkYIt8r~ojASjjE0cLgHB4JqA7b9hV9M0gpNYhgCmYHL5ZWAFHw__&Key-Pair-Id=KVTP0A1DKRTAX (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fec4734ff10>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 565, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 2909, in from_pretrained
    resolved_archive_file = cached_file(pretrained_model_name_or_path, filename, **cached_file_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 429, in cached_file
    resolved_file = hf_hub_download(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 1431, in hf_hub_download
    http_get(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 515, in http_get
    r = _request_wrapper(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 452, in _request_wrapper
    return http_backoff(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_http.py", line 258, in http_backoff
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Max retries exceeded with url: /bert-base-uncased/68d45e234eb4a928074dfd868cead0219ab85354cc53d20e772753c6bb9169d3?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27model.safetensors%3B+filename%3D%22model.safetensors%22%3B&Expires=1698901905&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5ODkwMTkwNX19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9iZXJ0LWJhc2UtdW5jYXNlZC82OGQ0NWUyMzRlYjRhOTI4MDc0ZGZkODY4Y2VhZDAyMTlhYjg1MzU0Y2M1M2QyMGU3NzI3NTNjNmJiOTE2OWQzP3Jlc3BvbnNlLWNvbnRlbnQtZGlzcG9zaXRpb249KiJ9XX0_&Signature=nO9ftAyr7QE8jCpcduTOKYQNT5Ty3o1MHjuMc6QVD6efkvXWzkxG7ZslK~ECruDr-0yJLUwJ~yTOdjkpXR9X5p16C5MPI-WEzsjnnEI7EDTrQawa~-DXdv6~6ljqneW0DHGbBuBke8~yL2sIkcniDZXYeGWD-Wy2PhDZd3-t~T0qC44lRGZqalrjN4RZMB6hWrWLlT2oK98RcH2BJd6IZmP8nwVJfHSLQdsDy3zIkA33MWNhO0e5x7aK33Fr610Jj2wY0CPu81rZw9fhzZZbX~6Ke4LwWCR0ob8CkYIt8r~ojASjjE0cLgHB4JqA7b9hV9M0gpNYhgCmYHL5ZWAFHw__&Key-Pair-Id=KVTP0A1DKRTAX (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fec4734ff10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"), '(Request ID: 020722e5-d9f5-485c-8e94-d37d002964d3)')
```

**Comment by jungchanghae** [comment]
3번의 AIL-K5G가 AIML-K가 맞을까요?
즉, 같은 네트워크인데 유선연결에서는 안되는데 무선연결시에는 된다는 이야기일까요..?

**Comment by cth127** [comment]
@jungchanghae 확인한 바론 AIL-K5G는 연구실 인터넷(광랜)이 아니라 이학관 인터넷이라고 합니다. 별개라고 합니다.

**Comment by wheresmadog** [comment]
I works just fine for me while I'm connecting via VPN -- which eventually routes through AIMLK LAN.

**Comment by cth127** [comment]
@wheresmadog 혹시 다음 코드가 정상적으로 작동하나요?

```python
from transformers import AutoModel
a = AutoModel.from_pretrained('distilbert-base-uncased')
```

**Comment by invigorator96** [comment]
Maybe @cth127 have been blocked by HF...?

**Comment by wheresmadog** [comment]
Ok, same error confirmed.

```
Downloading (…)lve/main/config.json: 100%|███████████████████████| 483/483 [00:00<00:00, 130kB/s]
Traceback (most recent call last):
  File "/home/wheresmadog/anaconda3/envs/fashion/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/wheresmadog/anaconda3/envs/fashion/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/wheresmadog/anaconda3/envs/fashion/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wheresmadog/anaconda3/envs/fashion/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/wheresmadog/anaconda3/envs/fashion/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/wheresmadog/anaconda3/envs/fashion/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/home/wheresmadog/anaconda3/envs/fashion/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/wheresmadog/anaconda3/envs/fashion/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f2551ef2b50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wheresmadog/anaconda3/envs/fashion/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/home/wheresmadog/anaconda3/envs/fashion/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/home/wheresmadog/anaconda3/envs/fashion/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Max retries exceeded with url: /distilbert-base-uncased/5e3f1108e3cb34ee048634875d8482665b65ac713291a7e32396fb18f6ff0063?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27model.safetensors%3B+filename%3D%22model.safetensors%22%3B&Expires=1698908579&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5ODkwODU3OX19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9kaXN0aWxiZXJ0LWJhc2UtdW5jYXNlZC81ZTNmMTEwOGUzY2IzNGVlMDQ4NjM0ODc1ZDg0ODI2NjViNjVhYzcxMzI5MWE3ZTMyMzk2ZmIxOGY2ZmYwMDYzP3Jlc3BvbnNlLWNvbnRlbnQtZGlzcG9zaXRpb249KiJ9XX0_&Signature=VKeemYPHC42LtH3lH8pXoxn3YOxLAlSqQ1Wdg3rBjyf1fFxx8-~lalaJ9N5Ex2SqTQ9hVZoBEOVtfirl1KxQkqj2MwJ9irhmQ7skb2HqXAXE4zbt5OsZR2ECzDy~ZNyYID0fytLAE1Z2YiVKaYsqqR~~SbkkieOfWEz6f36pkxL06RefyeudZ2ZZLH9jdCGx4kTqEdo7VWg18amvGh7KrUO995CRGhHJvD9BuXOnDAb2c80drjXBVkXNsVZ6DtjI4eW3LFqJ7dU5I41sqPJeTD48H0PoBLn9I-iPszSPKDyO5GTKtIZj7IqZjG--dchh09tJVafrHd-auzMAn4uZ0A__&Key-Pair-Id=KVTP0A1DKRTAX (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2551ef2b50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "foo.py", line 2, in <module>
    a = AutoModel.from_pretrained('distilbert-base-uncased')
  File "/home/wheresmadog/anaconda3/envs/fashion/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 565, in from_pretrained
    return model_class.from_pretrained(
  File "/home/wheresmadog/anaconda3/envs/fashion/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2909, in from_pretrained
    resolved_archive_file = cached_file(pretrained_model_name_or_path, filename, **cached_file_kwargs)
  File "/home/wheresmadog/anaconda3/envs/fashion/lib/python3.8/site-packages/transformers/utils/hub.py", line 429, in cached_file
    resolved_file = hf_hub_download(
  File "/home/wheresmadog/anaconda3/envs/fashion/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/wheresmadog/anaconda3/envs/fashion/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1364, in hf_hub_download
    http_get(
  File "/home/wheresmadog/anaconda3/envs/fashion/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 505, in http_get
    r = _request_wrapper(
  File "/home/wheresmadog/anaconda3/envs/fashion/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 442, in _request_wrapper
    return http_backoff(
  File "/home/wheresmadog/anaconda3/envs/fashion/lib/python3.8/site-packages/huggingface_hub/utils/_http.py", line 258, in http_backoff
    response = session.request(method=method, url=url, **kwargs)
  File "/home/wheresmadog/anaconda3/envs/fashion/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wheresmadog/anaconda3/envs/fashion/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/wheresmadog/anaconda3/envs/fashion/lib/python3.8/site-packages/huggingface_hub/utils/_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "/home/wheresmadog/anaconda3/envs/fashion/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Max retries exceeded with url: /distilbert-base-uncased/5e3f1108e3cb34ee048634875d8482665b65ac713291a7e32396fb18f6ff0063?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27model.safetensors%3B+filename%3D%22model.safetensors%22%3B&Expires=1698908579&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5ODkwODU3OX19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9kaXN0aWxiZXJ0LWJhc2UtdW5jYXNlZC81ZTNmMTEwOGUzY2IzNGVlMDQ4NjM0ODc1ZDg0ODI2NjViNjVhYzcxMzI5MWE3ZTMyMzk2ZmIxOGY2ZmYwMDYzP3Jlc3BvbnNlLWNvbnRlbnQtZGlzcG9zaXRpb249KiJ9XX0_&Signature=VKeemYPHC42LtH3lH8pXoxn3YOxLAlSqQ1Wdg3rBjyf1fFxx8-~lalaJ9N5Ex2SqTQ9hVZoBEOVtfirl1KxQkqj2MwJ9irhmQ7skb2HqXAXE4zbt5OsZR2ECzDy~ZNyYID0fytLAE1Z2YiVKaYsqqR~~SbkkieOfWEz6f36pkxL06RefyeudZ2ZZLH9jdCGx4kTqEdo7VWg18amvGh7KrUO995CRGhHJvD9BuXOnDAb2c80drjXBVkXNsVZ6DtjI4eW3LFqJ7dU5I41sqPJeTD48H0PoBLn9I-iPszSPKDyO5GTKtIZj7IqZjG--dchh09tJVafrHd-auzMAn4uZ0A__&Key-Pair-Id=KVTP0A1DKRTAX (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2551ef2b50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))"), '(Request ID: ec9b56c5-374a-4ad3-8224-6a708472c114)')
```

**Comment by cth127** [comment]
@wheresmadog 저 모델만 문제인 건 아닌 게 다른 모델에 대해서도 마찬가지입니다. 

>It works just fine for me

이건 아마 로컬에 cached 된 모델을 가져온 것으로 추정됨

**Comment by pinga999** [comment]
https://vhrehfdl.tistory.com/139

이런식의 git clone도 불가한가요?

**Comment by cth127** [comment]
@pinga999 clone을 하면 작은 파일들만 받아지고 큰 파라미터 파일은 안 받아집니다.

**Comment by pinga999** [comment]
https://github.com/huggingface/transformers/issues/17611

**Comment by cth127** [comment]
> downgrading requests to 2.27.1
import os
os.environ['CURL_CA_BUNDLE'] = ''

찾아서 시도해보았으나 안 됩니다ㅜ

**Comment by wheresmadog** [comment]
This issue is mainly caused by DNS error.

If you send ping for this `cdn-lfs.huggingface.co` link which probably contains LFS-updated files on HuggingFace (e.g., model parameters, hence large in size), it will simply output "Unknown host".

**Comment by wheresmadog** [comment]
Please refer here: https://stackoverflow.com/a/65918837

Please be aware that this is only a temporary solution. Whatever happened or not happened on Uni's or our LAN's DNS server, this issue should be resolved properly instead of this cheap workaround.

**Comment by d-h-lee** [comment]
가능한 시나리오 두가지를 제안해봅니다:

- 저희 게이트웨이 내부문제 --> 리셋 해보면 알수있음
- 저희 게이트웨이의 IP가 HF에서 블랙리스트에 올라감 (너무 많이 받았나?) --> https://github.com/huggingface/transformers/issues/21129 이런 식으로 대응을 할 수 있군요

**Comment by cth127** [comment]
@wheresmadog 됩니다! 고마워요! 

@d-h-lee 한번 24시간 뒤에도 재생산이 되는지 봐야할 것 같군요!

> @trianxy it seems like that the IP "spammed" the hub and you got rate limited. Did you ran some sort of loop to load stuff? The restriction should be lifted after 24h

**Comment by cth127** [comment]
24시간이 지났지만 마찬가지군요..

**Comment by invigorator96** [comment]
우리 게이트웨이에서 블로킹을 하고 있을 가능성이 보입니다. 저는 오늘 슬랙 접속이 안 되네요 ㅎㅎ;;;

**Comment by jungchanghae** [comment]
Secondary DNS 추가로 resolve했습니다.
